spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inteceptor_db
    username: postgres
    password: 123079
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


